---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/group: dc1
  bgpInstances:
  - name: "dc1"
    localASN: 65012
    peers:
    - name: "router1"
      peerASN: 65011
      peerAddress: "192.168.20.1"
      peerConfigRef:
        name: "cilium-peer"
        
---

apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      topology.kubernetes.io/group: dc2
  bgpInstances:
  - name: "dc2"
    localASN: 65012
    peers:
    - name: "router2"
      peerASN: 65011
      peerAddress: "192.168.120.1"
      peerConfigRef:
        name: "cilium-peer"
        
---

apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
    connectRetryTimeSeconds: 120
  ebgpMultihop: 4
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"

---

apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "PodCIDR"
    - advertisementType: "Service"
      service:
        addresses:
          - ClusterIP
          - ExternalIP
          - LoadBalancerIP
